//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface Observer extends com.zeroc.Ice.Object
{
    void receiveAudio(byte[] data, com.zeroc.Ice.Current current);

    void receiveAudioMessage(byte[] data, com.zeroc.Ice.Current current);

    void receiveAudioMessageGroup(String groupId, byte[] data, com.zeroc.Ice.Current current);

    void incomingCall(String fromUser, com.zeroc.Ice.Current current);

    void callAccepted(String fromUser, com.zeroc.Ice.Current current);

    void callRejected(String fromUser, com.zeroc.Ice.Current current);

    void callColgada(String fromUser, com.zeroc.Ice.Current current);

    void incomingGroupCall(String groupId, String fromUser, String[] members, com.zeroc.Ice.Current current);

    void groupCallUpdated(String groupId, String[] members, com.zeroc.Ice.Current current);

    void groupCallEnded(String groupId, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Demo::Observer",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Demo::Observer";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_receiveAudio(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        byte[] iceP_data;
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.receiveAudio(iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_receiveAudioMessage(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        byte[] iceP_data;
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.receiveAudioMessage(iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_receiveAudioMessageGroup(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupId;
        byte[] iceP_data;
        iceP_groupId = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.receiveAudioMessageGroup(iceP_groupId, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_incomingCall(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        iceP_fromUser = istr.readString();
        inS.endReadParams();
        obj.incomingCall(iceP_fromUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_callAccepted(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        iceP_fromUser = istr.readString();
        inS.endReadParams();
        obj.callAccepted(iceP_fromUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_callRejected(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        iceP_fromUser = istr.readString();
        inS.endReadParams();
        obj.callRejected(iceP_fromUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_callColgada(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        iceP_fromUser = istr.readString();
        inS.endReadParams();
        obj.callColgada(iceP_fromUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_incomingGroupCall(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupId;
        String iceP_fromUser;
        String[] iceP_members;
        iceP_groupId = istr.readString();
        iceP_fromUser = istr.readString();
        iceP_members = istr.readStringSeq();
        inS.endReadParams();
        obj.incomingGroupCall(iceP_groupId, iceP_fromUser, iceP_members, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_groupCallUpdated(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupId;
        String[] iceP_members;
        iceP_groupId = istr.readString();
        iceP_members = istr.readStringSeq();
        inS.endReadParams();
        obj.groupCallUpdated(iceP_groupId, iceP_members, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_groupCallEnded(Observer obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupId;
        iceP_groupId = istr.readString();
        inS.endReadParams();
        obj.groupCallEnded(iceP_groupId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "callAccepted",
        "callColgada",
        "callRejected",
        "groupCallEnded",
        "groupCallUpdated",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "incomingCall",
        "incomingGroupCall",
        "receiveAudio",
        "receiveAudioMessage",
        "receiveAudioMessageGroup"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_callAccepted(this, in, current);
            }
            case 1:
            {
                return _iceD_callColgada(this, in, current);
            }
            case 2:
            {
                return _iceD_callRejected(this, in, current);
            }
            case 3:
            {
                return _iceD_groupCallEnded(this, in, current);
            }
            case 4:
            {
                return _iceD_groupCallUpdated(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 9:
            {
                return _iceD_incomingCall(this, in, current);
            }
            case 10:
            {
                return _iceD_incomingGroupCall(this, in, current);
            }
            case 11:
            {
                return _iceD_receiveAudio(this, in, current);
            }
            case 12:
            {
                return _iceD_receiveAudioMessage(this, in, current);
            }
            case 13:
            {
                return _iceD_receiveAudioMessageGroup(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
