//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface SubjectPrx extends com.zeroc.Ice.ObjectPrx
{
    default void attach(String userId, ObserverPrx obs)
    {
        attach(userId, obs, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void attach(String userId, ObserverPrx obs, java.util.Map<String, String> context)
    {
        _iceI_attachAsync(userId, obs, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> attachAsync(String userId, ObserverPrx obs)
    {
        return _iceI_attachAsync(userId, obs, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> attachAsync(String userId, ObserverPrx obs, java.util.Map<String, String> context)
    {
        return _iceI_attachAsync(userId, obs, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_obs -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_attachAsync(String iceP_userId, ObserverPrx iceP_obs, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "attach", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeProxy(iceP_obs);
                 }, null);
        return f;
    }

    default void sendAudio(String fromUser, byte[] data)
    {
        sendAudio(fromUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudio(String fromUser, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioAsync(fromUser, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioAsync(String fromUser, byte[] data)
    {
        return _iceI_sendAudioAsync(fromUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioAsync(String fromUser, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioAsync(fromUser, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioAsync(String iceP_fromUser, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudio", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default void sendAudioMessage(String fromUser, String toUser, byte[] data)
    {
        sendAudioMessage(fromUser, toUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudioMessage(String fromUser, String toUser, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioMessageAsync(fromUser, toUser, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioMessageAsync(String fromUser, String toUser, byte[] data)
    {
        return _iceI_sendAudioMessageAsync(fromUser, toUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioMessageAsync(String fromUser, String toUser, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioMessageAsync(fromUser, toUser, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioMessageAsync(String iceP_fromUser, String iceP_toUser, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudioMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default String[] getConnectedUsers()
    {
        return getConnectedUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] getConnectedUsers(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> getConnectedUsersAsync()
    {
        return _iceI_getConnectedUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> getConnectedUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getConnectedUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_getConnectedUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getConnectedUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default void startCall(String fromUser, String toUser)
    {
        startCall(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void startCall(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_startCallAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> startCallAsync(String fromUser, String toUser)
    {
        return _iceI_startCallAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> startCallAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_startCallAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startCallAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default void acceptCall(String fromUser, String toUser)
    {
        acceptCall(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void acceptCall(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_acceptCallAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> acceptCallAsync(String fromUser, String toUser)
    {
        return _iceI_acceptCallAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> acceptCallAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_acceptCallAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_acceptCallAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "acceptCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default void rejectCall(String fromUser, String toUser)
    {
        rejectCall(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void rejectCall(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_rejectCallAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> rejectCallAsync(String fromUser, String toUser)
    {
        return _iceI_rejectCallAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> rejectCallAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_rejectCallAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_rejectCallAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rejectCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default void colgar(String fromUser, String toUser)
    {
        colgar(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void colgar(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        _iceI_colgarAsync(fromUser, toUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> colgarAsync(String fromUser, String toUser)
    {
        return _iceI_colgarAsync(fromUser, toUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> colgarAsync(String fromUser, String toUser, java.util.Map<String, String> context)
    {
        return _iceI_colgarAsync(fromUser, toUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_toUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_colgarAsync(String iceP_fromUser, String iceP_toUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "colgar", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_toUser);
                 }, null);
        return f;
    }

    default String createGroupCall(String fromUser, String[] users)
    {
        return createGroupCall(fromUser, users, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String createGroupCall(String fromUser, String[] users, java.util.Map<String, String> context)
    {
        return _iceI_createGroupCallAsync(fromUser, users, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createGroupCallAsync(String fromUser, String[] users)
    {
        return _iceI_createGroupCallAsync(fromUser, users, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> createGroupCallAsync(String fromUser, String[] users, java.util.Map<String, String> context)
    {
        return _iceI_createGroupCallAsync(fromUser, users, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_users -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_createGroupCallAsync(String iceP_fromUser, String[] iceP_users, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroupCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeStringSeq(iceP_users);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void joinGroupCall(String groupId, String user)
    {
        joinGroupCall(groupId, user, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void joinGroupCall(String groupId, String user, java.util.Map<String, String> context)
    {
        _iceI_joinGroupCallAsync(groupId, user, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> joinGroupCallAsync(String groupId, String user)
    {
        return _iceI_joinGroupCallAsync(groupId, user, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> joinGroupCallAsync(String groupId, String user, java.util.Map<String, String> context)
    {
        return _iceI_joinGroupCallAsync(groupId, user, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupId -
     * @param iceP_user -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_joinGroupCallAsync(String iceP_groupId, String iceP_user, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinGroupCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_groupId);
                     ostr.writeString(iceP_user);
                 }, null);
        return f;
    }

    default void leaveGroupCall(String groupId, String user)
    {
        leaveGroupCall(groupId, user, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void leaveGroupCall(String groupId, String user, java.util.Map<String, String> context)
    {
        _iceI_leaveGroupCallAsync(groupId, user, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> leaveGroupCallAsync(String groupId, String user)
    {
        return _iceI_leaveGroupCallAsync(groupId, user, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> leaveGroupCallAsync(String groupId, String user, java.util.Map<String, String> context)
    {
        return _iceI_leaveGroupCallAsync(groupId, user, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupId -
     * @param iceP_user -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_leaveGroupCallAsync(String iceP_groupId, String iceP_user, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "leaveGroupCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_groupId);
                     ostr.writeString(iceP_user);
                 }, null);
        return f;
    }

    default void sendAudioMessageGroup(String fromUser, String groupId, byte[] data)
    {
        sendAudioMessageGroup(fromUser, groupId, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudioMessageGroup(String fromUser, String groupId, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioMessageGroupAsync(fromUser, groupId, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioMessageGroupAsync(String fromUser, String groupId, byte[] data)
    {
        return _iceI_sendAudioMessageGroupAsync(fromUser, groupId, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioMessageGroupAsync(String fromUser, String groupId, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioMessageGroupAsync(fromUser, groupId, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_fromUser -
     * @param iceP_groupId -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioMessageGroupAsync(String iceP_fromUser, String iceP_groupId, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudioMessageGroup", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_groupId);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default void sendAudioGroup(String groupId, String fromUser, byte[] data)
    {
        sendAudioGroup(groupId, fromUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudioGroup(String groupId, String fromUser, byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioGroupAsync(groupId, fromUser, data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioGroupAsync(String groupId, String fromUser, byte[] data)
    {
        return _iceI_sendAudioGroupAsync(groupId, fromUser, data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioGroupAsync(String groupId, String fromUser, byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioGroupAsync(groupId, fromUser, data, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupId -
     * @param iceP_fromUser -
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioGroupAsync(String iceP_groupId, String iceP_fromUser, byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudioGroup", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_groupId);
                     ostr.writeString(iceP_fromUser);
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SubjectPrx.class, _SubjectPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SubjectPrx.class, _SubjectPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SubjectPrx.class, _SubjectPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubjectPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SubjectPrx.class, _SubjectPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SubjectPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SubjectPrx.class, _SubjectPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SubjectPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SubjectPrx.class, _SubjectPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SubjectPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SubjectPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SubjectPrx ice_adapterId(String newAdapterId)
    {
        return (SubjectPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SubjectPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SubjectPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SubjectPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SubjectPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SubjectPrx ice_invocationTimeout(int newTimeout)
    {
        return (SubjectPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SubjectPrx ice_connectionCached(boolean newCache)
    {
        return (SubjectPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SubjectPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SubjectPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SubjectPrx ice_secure(boolean b)
    {
        return (SubjectPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SubjectPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SubjectPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SubjectPrx ice_preferSecure(boolean b)
    {
        return (SubjectPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SubjectPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SubjectPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SubjectPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SubjectPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SubjectPrx ice_collocationOptimized(boolean b)
    {
        return (SubjectPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SubjectPrx ice_twoway()
    {
        return (SubjectPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SubjectPrx ice_oneway()
    {
        return (SubjectPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SubjectPrx ice_batchOneway()
    {
        return (SubjectPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SubjectPrx ice_datagram()
    {
        return (SubjectPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SubjectPrx ice_batchDatagram()
    {
        return (SubjectPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SubjectPrx ice_compress(boolean co)
    {
        return (SubjectPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SubjectPrx ice_timeout(int t)
    {
        return (SubjectPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SubjectPrx ice_connectionId(String connectionId)
    {
        return (SubjectPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SubjectPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SubjectPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::Subject";
    }
}
